const styles = {
  container: {
    maxWidth: '1400px',
    margin: '0 auto',
    padding: '24px',
    fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif',
  },
  header: { textAlign: 'center', marginBottom: '32px' },
  title: { fontSize: '2.5rem', marginBottom: '8px' },
  subtitle: { fontSize: '1.1rem', color: '#6c757d' },
  alertError: {
    backgroundColor: '#f8d7da',
    color: '#721c24',
    padding: '16px',
    borderRadius: '8px',
    marginBottom: '24px',
    borderLeft: '4px solid #dc3545',
  },
  alertSuccess: {
    backgroundColor: '#d4edda',
    color: '#155724',
    padding: '16px',
    borderRadius: '8px',
    marginBottom: '24px',
    borderLeft: '4px solid #28a745',
  },
  mainGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(500px, 1fr))',
    gap: '24px',
    marginBottom: '32px',
  },
  card: {
    backgroundColor: 'white',
    borderRadius: '12px',
    padding: '24px',
    boxShadow: '0 2px 8px rgba(0,0,0,0.1)',
  },
  cardTitle: { fontSize: '1.5rem', color: '#2c3e50', marginTop: 0, marginBottom: '20px' },
  infoBox: {
    backgroundColor: '#e3f2fd',
    padding: '16px',
    borderRadius: '8px',
    marginBottom: '24px',
    borderLeft: '4px solid #2196f3',
    fontSize: '14px',
  },
  infoList: { margin: '8px 0 0 20px', padding: 0, color: '#000000ff' },
  formGroup: { marginBottom: '24px' },
  label: { display: 'block', fontWeight: '600', marginBottom: '8px', color: '#495057' },
  input: {
    width: '100%',
    padding: '12px',
    fontSize: '16px',
    border: '2px solid #dee2e6',
    borderRadius: '8px',
    marginBottom: '8px',
    boxSizing: 'border-box',
  },
  slider: {
    width: '100%',
    height: '8px',
    borderRadius: '4px',
    background: 'linear-gradient(to right, #667eea, #764ba2)',
    outline: 'none',
    marginTop: '8px',
  },
  rangeLabels: { display: 'flex', justifyContent: 'space-between', fontSize: '12px', color: '#6c757d', marginTop: '4px' },
  rangeValue: { fontWeight: 'bold', color: '#667eea', fontSize: '14px' },
  buttonGroup: { display: 'flex', gap: '12px' },
  button: { flex: 1, padding: '12px 24px', fontSize: '16px', fontWeight: '600', border: 'none', borderRadius: '8px', cursor: 'pointer', transition: 'all 0.3s' },
  buttonPrimary: { background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)', color: 'white' },
  buttonSecondary: { backgroundColor: '#f8f9fa', color: '#495057', border: '1px solid #dee2e6' },
  buttonDisabled: { opacity: 0.6, cursor: 'not-allowed' },
  badge: { display: 'inline-block', padding: '8px 16px', borderRadius: '20px', fontSize: '14px', fontWeight: '600', marginBottom: '20px' },
  badgeSuccess: { backgroundColor: '#d4edda', color: '#155724' },
  badgeError: { backgroundColor: '#f8d7da', color: '#721c24' },
  badgeNeutral: { backgroundColor: '#e2e3e5', color: '#343a40' },
  cuotaBox: { backgroundColor: '#f0f4ff', padding: '24px', borderRadius: '12px', textAlign: 'center', marginBottom: '24px' },
  cuotaLabel: { fontSize: '14px', color: '#6c757d', marginBottom: '8px' },
  cuotaValue: { fontSize: '36px', fontWeight: 'bold', color: '#667eea' },
  cuotaSubtext: { fontSize: '14px', color: '#6c757d', marginTop: '8px' },
  detailsGrid: { display: 'grid', gridTemplateColumns: '1fr', gap: '12px', marginBottom: '20px' },
  detailItem: { display: 'flex', justifyContent: 'space-between', padding: '12px', backgroundColor: '#f8f9fa', borderRadius: '6px', fontSize: '14px', color: 'black' },
  warningBox: { backgroundColor: '#fff3cd', padding: '16px', borderRadius: '8px', borderLeft: '4px solid #ffc107', fontSize: '14px', color: '#856404' },
  emptyState: { textAlign: 'center', padding: '48px 24px', color: '#6c757d' },
  savedSimInfo: { backgroundColor: '#f8f9fa', padding: '16px', borderRadius: '8px', textAlign: 'center' },
  table: { width: '100%', borderCollapse: 'collapse', fontSize: '14px' },
  th: { backgroundColor: '#f8f9fa', padding: '12px', textAlign: 'left', fontWeight: '600', borderBottom: '2px solid #dee2e6' },
  td: { padding: '12px', borderBottom: '1px solid #dee2e6' },
  trEven: { backgroundColor: '#f8f9fa' },
  loading: { textAlign: 'center', padding: '48px', color: '#6c757d' },
  spinner: { border: '4px solid #f3f3f3', borderTop: '4px solid #667eea', borderRadius: '50%', width: '40px', height: '40px', animation: 'spin 1s linear infinite', margin: '0 auto 16px' },
  historialGrid: { display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(280px, 1fr))', gap: '16px', marginBottom: '16px' },
  historialCard: { backgroundColor: 'white', border: '2px solid #dee2e6', borderRadius: '12px', padding: '16px', cursor: 'pointer', transition: 'all 0.3s', color: 'black' },
  historialHeader: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '12px' },
  historialBadge: { fontSize: '11px', padding: '4px 8px', borderRadius: '12px' },
  deleteButton: { background: 'none', border: 'none', fontSize: '18px', cursor: 'pointer', padding: '4px 8px' },
  historialCuota: { marginBottom: '16px' },
  historialCuotaValue: { fontSize: '24px', fontWeight: 'bold', color: '#667eea' },
  historialCuotaLabel: { fontSize: '12px', color: '#6c757d' },
  historialDetails: { fontSize: '14px', marginBottom: '12px' },
  historialDetailRow: { display: 'flex', justifyContent: 'space-between', marginBottom: '4px' },
  historialFooter: { fontSize: '11px', color: '#999', paddingTop: '12px', borderTop: '1px solid #eee' },
};

export default styles;
