services:
  app:
    build: ./server
    ports:
      - "3000:3000"
    env_file:
      - ./server/.env
    depends_on:
      - postgres_db
    volumes:
      - ./server:/app
      - /app/node_modules

  postgres_db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: