CREATE TABLE CLIENTE (
	RUT VARCHAR(9) PRIMARY KEY NOT NULL,
	NOMBRE_COMPLETO VARCHAR NOT NULL,
	SCORING INT,
	CORREO VARCHAR(100) UNIQUE,
	EDAD INT CHECK (
		EDAD >= 0
		AND EDAD <= 120
	),
	SEXO CHAR(1) CHECK (SEXO IN ('M', 'F')),
	TIPO_USUARIO INT
	FECHA_NACIMIENTO date not null,
);

CREATE TABLE CUENTA_BANCO_CLIENTE (
	NUMERO_CUENTA_SERIE VARCHAR PRIMARY KEY,
	RUT_PERSONA VARCHAR(9),
	NOMBRE_BANCO VARCHAR(100),
	ID_BANCO VARCHAR(11),
	TIPO_DE_CUENTA VARCHAR(20) CHECK (TIPO_DE_CUENTA IN ('Credito','Debito','Ahorro')),

	CONSTRAINT fk_usuario
		FOREIGN KEY (RUT_PERSONA)
		REFERENCES CLIENTE(RUT)
		ON UPDATE CASCADE
		ON DELETE CASCADE
);


CREATE TABLE TIPO_DOCUMENTOS(
	ID SERIAL PRIMARY KEY,
	NOMBRE VARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE CARPETA_DIGITAL_CLIENTE(
	ID SERIAL PRIMARY KEY,
	RUT_PERSONA VARCHAR(9) NOT NULL REFERENCES CLIENTE(RUT)
	    ON UPDATE CASCADE
        ON DELETE CASCADE,
	TIPO_DOCUMENTO INT NOT NULL REFERENCES TIPO_DOCUMENTOS(ID),
	ARCHIVO BYTEA NOT NULL,
	FECHA_SUBIDA TIMESTAMP DEFAULT NOW()
);


CREATE TABLE DATOS_SIMULACION(
	ID SERIAL PRIMARY KEY,
	RUT_SIMULACION VARCHAR(9) REFERENCES cliente(rut) ON UPDATE CASCADE ON DELETE CASCADE,
	MONTO INT NOT NULL,
	CUOTAS INT NOT NULL,
	TARIFAS INT NOT NULL,
	TOTAL_A_PAGAR INT NOT NULL,
	FECHA_DE_SIMULACION TIMESTAMP DEFAULT NOW()
)

CREATE TABLE CAMPANA_CORREO (
    ID SERIAL PRIMARY KEY,
	RUT_CAMPANA VARCHAR(9) NOT NULL REFERENCES CLIENTE (RUT) ON UPDATE CASCADE ON DELETE CASCADE,
	CORREO_CLIENTE VARCHAR(100) NOT NULL,
	ESTADO BOOLEAN NOT NULL,
    ACEPTADO BOOLEAN NOT NULL,
    FECHA_ENVIO TIMESTAMP DEFAULT NOW()
);